Feat/uploading
mkh-wtag/blog-app pull request #7
Opened 2024-01-10 05:40 UTC by mkh-wtag

Complete image uploading feature

2024-01-15 07:55 UTC, hhu-wtag requested changes

2024-01-15 07:55 UTC, hhu-wtag commented on src/app.scss
> +}
If it's empty, can we remove it?

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/Dashboard.jsx
> +      setPostList(newPostList);
We generally avoid the words list, items appended to variable names. 
So,
`postList` ❌ 
`posts` ✅ 

If it's not a huge change, I would suggest the change. Otherwise we can continue.

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/Dashboard.jsx
> +  const onSubmitComment = (comment, postid) => {
```suggestion
  const onSubmitComment = (comment, postId) => {
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/Dashboard.jsx
> +      } else return post;
redundant else
```suggestion
      }
      return post;
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/Dashboard.jsx
> +  };
We can use javascript object reference to make this more simple.
```suggestion
  const onDeleteComment = (postId, commentId) => {
    const _posts = [...postList]
    
    const post = _posts.find(({id}) => id === postId)
    
    if(post === undefined){
        return
    }
    
    post.comments = post.comments.filter(({id}) => id !== commentId)
    
    setPostList(_posts);
    localStorage.setItem("posts", JSON.stringify(_posts));
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/EditProfile.jsx
> +      } else return user;
```suggestion
      }
      
      return user;
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/PostList.jsx
>        {postList?.map((post) => {
postList should always be empty array. So no need to set it to `null` or `undefined`.
```suggestion
      {postList.map((post) => {
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/PostList.jsx
> +  const [writeComment, setWriteComment] = useState("");
```suggestion
  const [comment, setComment] = useState("");
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/PostList.jsx
> +  };
Let's avoid short circuiting while we can. Writing maintainable code is hard. So we should always target simplicity.
```suggestion
  const submitComment = (id) => {
    if(comment.trim() === ""){
       return
    }
    
    onSubmitComment(writeComment, id);
    setComment("");
  };
```

2024-01-15 07:55 UTC, hhu-wtag commented on src/components/PostList.jsx
> +                      value={writeComment}
```suggestion
                      className="input-field area"
                      placeholder="Enter your valuable comment."
                      value={comment}
```

2024-01-15 09:25 UTC, mkh-wtag commented on src/components/Dashboard.jsx
> +      setPostList(newPostList);
It was `posts` at first but Araf said `posts` and `post` are so similar that they might create confusion so I changed it to `postList`. Now they appear in 32 places and looks confusing to change. But I will keep your suggestions in mind.

2024-01-17 06:38 UTC, hhu-wtag approved these changes

2024-01-17 06:38 UTC, hhu-wtag commented on src/components/Dashboard.jsx
> +      setPostList(newPostList);
Sure no worries bhai.

2024-01-17 06:44 UTC, merged